spring.application.name=myFirstProject
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver.protocol.command=DEBUG
#debug=true
#spring.data.mongodb.username=
#spring.data.mongodb.password=